version: '3.8'

# 此docker-compose 无法执行跟--abort-on-container-exit指令，这样会导致只有一个project被启动，只能运行
# docker-compose up -d --build
# 之后可以执行 docker-compose logs [serializable|read_committed|read_un_committed|repeatable_read]查看对应输出结果
# 最后执行
# docker-compose rm -f 
# 删除对应容器回收资源
services:
  mysql:
    container_name: test_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  read_un_committed:
    container_name: read_un_committed
    build: ./1.读未提交
  read_committed:
    container_name: read_committed
    build: ./2.读已提交
  repeatable_read:
    container_name: repeatable_read
    build: ./3.可重复读
  serializable:
    container_name: serializable
    build: ./4.串行化